/* Generated from data/products.json — do not invent prices */
window.HANA_DATA = {
  "brand": "Hana 3abaya",
  "domain": "hana3abaya.com",
  "whatsapp": "201010000533",
  "whatsapp_display": "01010000533",
  "currency": "EGP",
  "products": [
    {
      "id": "HN-001",
      "name": "عباية قطعتين",
      "whatsapp_name": "عباية قطعتين",
      "category": "عباية",
      "price": 1400,
      "compare_at": 1650,
      "sizes": "XL — نصف محيط الصدر 58 سم | 2XL — نصف محيط الصدر 60 سم",
      "colors": "المعروض فقط",
      "material": "كتان إسباني",
      "description": "عباية قطعتين بيزيك كت وكارديجان",
      "stock": 2,
      "availability": "متاح",
      "care": "يفضل الغسيل اليدوي",
      "featured": false
    },
    {
      "id": "HN-002",
      "name": "كارديجان مخطط برباط",
      "whatsapp_name": "كارديجان مخطط برباط",
      "category": "كارديجان",
      "price": 1050,
      "compare_at": 1250,
      "sizes": "2XL — نصف محيط الصدر 56 سم | 4XL — نصف محيط الصدر 60 سم",
      "colors": "المعروض فقط",
      "material": "ريون تركي",
      "description": "كارديجان فقط بحزام داخلي وخارجي",
      "stock": 2,
      "availability": "متاح",
      "care": "يفضل الغسيل اليدوي",
      "featured": false
    },
    {
      "id": "HN-003",
      "name": "عباية كتان إسباني بترولي",
      "whatsapp_name": "عباية كتان إسباني بترولي",
      "category": "عباية",
      "price": 1400,
      "compare_at": 1650,
      "sizes": "مقاس 48 — نصف محيط الصدر 60 سم | مقاس 50 — نصف محيط الصدر 64 سم",
      "colors": "المعروض فقط",
      "material": "روز كريب",
      "description": "عباية كاجوال من الكتان الإسباني",
      "stock": 2,
      "availability": "متاح",
      "care": "يفضل الغسيل اليدوي",
      "featured": false
    },
    {
      "id": "HN-004",
      "name": "فستان كريب ستان كحلي",
      "whatsapp_name": "فستان كريب ستان كحلي",
      "category": "فستان",
      "price": 1200,
      "compare_at": 1500,
      "sizes": "مقاس 46 — نصف محيط الصدر 56 سم | مقاس 48 — نصف محيط الصدر 58 سم | مقاس 50 — نصف محيط الصدر 60 سم | مقاس 52 — نصف محيط الصدر 62 سم",
      "colors": "المعروض فقط",
      "material": "كريب ستان",
      "description": "فستان من كريب ستان مع إكسسوار بسيط",
      "stock": 4,
      "availability": "متاح",
      "care": "يفضل الغسيل اليدوي",
      "featured": false
    },
    {
      "id": "HN-005",
      "name": "فستان ستان مبطن أوف وايت",
      "whatsapp_name": "فستان ستان مبطن أوف وايت",
      "category": "فستان",
      "price": 1300,
      "compare_at": 1550,
      "sizes": "M — نصف محيط الصدر 52 سم | XL — نصف محيط الصدر 56 سم | 2XL — نصف محيط الصدر 60 سم",
      "colors": "المعروض فقط",
      "material": "ستان",
      "description": "فستان من الستان مع بطانة كاملة",
      "stock": 3,
      "availability": "متاح",
      "care": "يفضل الغسيل اليدوي",
      "featured": false
    },
    {
      "id": "HN-006",
      "name": "فستان واسع الأكمام سماوي",
      "whatsapp_name": "فستان واسع الأكمام سماوي",
      "category": "فستان",
      "price": 1300,
      "compare_at": 1550,
      "sizes": "M — نصف محيط الصدر 52 سم | XL — نصف محيط الصدر 56 سم | 2XL — نصف محيط الصدر 60 سم",
      "colors": "المعروض فقط",
      "material": "ريون تركي",
      "description": "فستان بناتي بأكمام واسعة مبطن بطانة كاملة",
      "stock": 3,
      "availability": "متاح",
      "care": "يفضل الغسيل اليدوي",
      "featured": false
    },
    {
      "id": "HN-007",
      "name": "فستان واسع الأكمام باستيل",
      "whatsapp_name": "فستان واسع الأكمام باستيل",
      "category": "فستان",
      "price": 1300,
      "compare_at": 1550,
      "sizes": "M — نصف محيط الصدر 52 سم | XL — نصف محيط الصدر 56 سم | 2XL — نصف محيط الصدر 60 سم",
      "colors": "المعروض فقط",
      "material": "ريون تركي",
      "description": "فستان بناتي بأكمام واسعة مبطن بطانة كاملة",
      "stock": 3,
      "availability": "متاح",
      "care": "يفضل الغسيل اليدوي",
      "featured": false
    },
    {
      "id": "HN-008",
      "name": "فستان طاير مبطن مينت",
      "whatsapp_name": "فستان طاير مبطن مينت",
      "category": "فستان",
      "price": 950,
      "compare_at": 1250,
      "sizes": "مقاس 46 — نصف محيط الصدر 56 سم",
      "colors": "المعروض فقط",
      "material": "أقطان",
      "description": "فستان بقصة طايرة من الصدر وبطانة",
      "stock": 1,
      "availability": "متاح",
      "care": "يفضل الغسيل اليدوي",
      "featured": false
    },
    {
      "id": "HN-009",
      "name": "فستان كتان فرنسي زيتوني",
      "whatsapp_name": "فستان كتان فرنسي زيتوني",
      "category": "فستان",
      "price": 1200,
      "compare_at": 1400,
      "sizes": "مقاس 40 — نصف محيط الصدر 52 سم | مقاس 46 — نصف محيط الصدر 58 سم",
      "colors": "المعروض فقط",
      "material": "كتان فرنسي",
      "description": "فستان من الكتان الفرنسي الناعم والمريح جدا",
      "stock": 2,
      "availability": "متاح",
      "care": "يفضل الغسيل اليدوي",
      "featured": false
    },
    {
      "id": "HN-010",
      "name": "عباية قطنية منقوشة بيج",
      "whatsapp_name": "عباية قطنية منقوشة بيج",
      "category": "عباية",
      "price": 1250,
      "compare_at": 1500,
      "sizes": "مقاس 46 — نصف محيط الصدر 58 سم | مقاس 48 — نصف محيط الصدر 60 سم",
      "colors": "المعروض فقط",
      "material": "كتان بارز",
      "description": "عباية فستان من خامة قطنية مع نقشة بارزة",
      "stock": 2,
      "availability": "متاح",
      "care": "يفضل الغسيل اليدوي",
      "featured": false
    },
    {
      "id": "HN-011",
      "name": "عباية روز كريب مطرزة أزرق",
      "whatsapp_name": "عباية روز كريب مطرزة أزرق",
      "category": "عباية",
      "price": 1250,
      "compare_at": 1450,
      "sizes": "مقاس 48 — نصف محيط الصدر 60 سم | مقاس 50 — نصف محيط الصدر 62 سم",
      "colors": "المعروض فقط",
      "material": "روز كريب",
      "description": "عباية من الروز كريب مع تطريز من الخيط البارز",
      "stock": 2,
      "availability": "متاح",
      "care": "يفضل الغسيل اليدوي",
      "featured": false
    },
    {
      "id": "HN-012",
      "name": "عباية مطرزة موف",
      "whatsapp_name": "عباية مطرزة موف",
      "category": "عباية",
      "price": 1150,
      "compare_at": 1350,
      "sizes": "مقاس 46 — نصف محيط الصدر 56 سم | مقاس 50 — نصف محيط الصدر 62 سم | مقاس 52 — نصف محيط الصدر 62 سم",
      "colors": "المعروض فقط",
      "material": "أقطان",
      "description": "فستان قطعة واحدة روز كريب بتوكة على الصدر",
      "stock": 3,
      "availability": "متاح",
      "care": "يفضل الغسيل اليدوي",
      "featured": false
    },
    {
      "id": "HN-013",
      "name": "طقم حرير مطبوع أوف وايت",
      "whatsapp_name": "طقم حرير مطبوع أوف وايت",
      "category": "طقم",
      "price": 1450,
      "compare_at": 1600,
      "sizes": "مقاس 48 — نصف محيط الصدر 58 سم | مقاس 52 — نصف محيط الصدر 66 سم",
      "colors": "المعروض فقط",
      "material": "",
      "description": "سوت من الحرير المطبوع عبارة عن تونيك طويل وجيب بليسيه",
      "stock": 2,
      "availability": "متاح",
      "care": "يفضل الغسيل اليدوي",
      "featured": false
    },
    {
      "id": "HN-014",
      "name": "طقم حرير مطبوع نبيتي",
      "whatsapp_name": "طقم حرير مطبوع نبيتي",
      "category": "طقم",
      "price": 1450,
      "compare_at": 1600,
      "sizes": "مقاس 48 — نصف محيط الصدر 58 سم | مقاس 52 — نصف محيط الصدر 66 سم",
      "colors": "المعروض فقط",
      "material": "",
      "description": "سوت من الحرير المطبوع عبارة عن تونيك طويل وجيب بليسيه",
      "stock": 2,
      "availability": "متاح",
      "care": "يفضل الغسيل اليدوي",
      "featured": false
    },
    {
      "id": "HN-015",
      "name": "لونج شميز بيج",
      "whatsapp_name": "لونج شميز بيج",
      "category": "لونج شميز",
      "price": 750,
      "compare_at": 1350,
      "sizes": "L — نصف محيط الصدر 58 سم | XL — نصف محيط الصدر 60 سم",
      "colors": "المعروض فقط",
      "material": "",
      "description": "كتان مطبوع طباعة بارزة",
      "stock": 2,
      "availability": "متاح",
      "care": "يفضل الغسيل اليدوي",
      "featured": false
    },
    {
      "id": "HN-016",
      "name": "لونج شميز سماوي",
      "whatsapp_name": "لونج شميز سماوي",
      "category": "لونج شميز",
      "price": 750,
      "compare_at": 1350,
      "sizes": "L — نصف محيط الصدر 58 سم | XL — نصف محيط الصدر 60 سم",
      "colors": "المعروض فقط",
      "material": "",
      "description": "كتان مطبوع طباعة بارزة",
      "stock": 2,
      "availability": "متاح",
      "care": "يفضل الغسيل اليدوي",
      "featured": false
    },
    {
      "id": "HN-017",
      "name": "لونج شميز أخضر",
      "whatsapp_name": "لونج شميز أخضر",
      "category": "لونج شميز",
      "price": 750,
      "compare_at": 1350,
      "sizes": "L — نصف محيط الصدر 58 سم | 3L — نصف محيط الصدر 64 سم",
      "colors": "المعروض فقط",
      "material": "",
      "description": "كتان مطبوع طباعة بارزة",
      "stock": 2,
      "availability": "متاح",
      "care": "يفضل الغسيل اليدوي",
      "featured": false
    },
    {
      "id": "HN-018",
      "name": "فستان حرير ناعم موف وأسود",
      "whatsapp_name": "فستان حرير ناعم موف وأسود",
      "category": "فستان",
      "price": 950,
      "compare_at": 1400,
      "sizes": "مقاس 46 — نصف محيط الصدر 58 سم | مقاس 48 — نصف محيط الصدر 60 سم | مقاس 50 — نصف محيط الصدر 62 سم | مقاس 52 — نصف محيط الصدر 64 سم",
      "colors": "المعروض فقط",
      "material": "",
      "description": "فستان قطعة واحدة من خامة الحرير الناعم والمريح",
      "stock": 4,
      "availability": "متاح",
      "care": "يفضل الغسيل اليدوي",
      "featured": false
    },
    {
      "id": "HN-019",
      "name": "فستان حرير ناعم أسود",
      "whatsapp_name": "فستان حرير ناعم أسود",
      "category": "فستان",
      "price": 950,
      "compare_at": 1400,
      "sizes": "مقاس 46 — نصف محيط الصدر 58 سم | مقاس 48 — نصف محيط الصدر 60 سم | مقاس 50 — نصف محيط الصدر 62 سم | مقاس 52 — نصف محيط الصدر 64 سم",
      "colors": "المعروض فقط",
      "material": "",
      "description": "فستان قطعة واحدة من خامة الحرير الناعم والمريح",
      "stock": 4,
      "availability": "متاح",
      "care": "يفضل الغسيل اليدوي",
      "featured": false
    },
    {
      "id": "HN-020",
      "name": "فستان قطعتين أوف وايت",
      "whatsapp_name": "فستان قطعتين أوف وايت",
      "category": "فستان",
      "price": 950,
      "compare_at": 1550,
      "sizes": "L — نصف محيط الصدر 58 سم | XL — نصف محيط الصدر 60 سم | 3XL — نصف محيط الصدر 64 سم",
      "colors": "المعروض فقط",
      "material": "",
      "description": "فستان قطعتين بيزيك طويل كت والقطعة التانية أقصر بلياقة قميص خامة قطنية",
      "stock": 3,
      "availability": "متاح",
      "care": "يفضل الغسيل اليدوي",
      "featured": false
    },
    {
      "id": "HN-021",
      "name": "فستان قطعتين رمادي",
      "whatsapp_name": "فستان قطعتين رمادي",
      "category": "فستان",
      "price": 950,
      "compare_at": 1550,
      "sizes": "L — نصف محيط الصدر 58 سم | XL — نصف محيط الصدر 60 سم | 3XL — نصف محيط الصدر 64 سم",
      "colors": "المعروض فقط",
      "material": "",
      "description": "فستان قطعتين بيزيك طويل كت والقطعة التانية أقصر بلياقة قميص خامة قطنية",
      "stock": 3,
      "availability": "متاح",
      "care": "يفضل الغسيل اليدوي",
      "featured": false
    },
    {
      "id": "HN-022",
      "name": "فستان شيفون كوري أخضر",
      "whatsapp_name": "فستان شيفون كوري أخضر",
      "category": "فستان",
      "price": 1400,
      "compare_at": 1750,
      "sizes": "مقاس 48 — نصف محيط الصدر 60 سم | مقاس 52 — نصف محيط الصدر 64 سم",
      "colors": "المعروض فقط",
      "material": "",
      "description": "فستان من الشيفون الكوري الناعم مبطن بطانة كاملة من السوفت",
      "stock": 2,
      "availability": "متاح",
      "care": "يفضل الغسيل اليدوي",
      "featured": false
    },
    {
      "id": "HN-023",
      "name": "عباية روز كريب رمادي",
      "whatsapp_name": "عباية روز كريب رمادي",
      "category": "عباية",
      "price": 950,
      "compare_at": 1250,
      "sizes": "مقاس 50 — نصف محيط الصدر 62 سم | مقاس 52 — نصف محيط الصدر 64 سم | مقاس 54 — نصف محيط الصدر 66 سم | مقاس 56 — نصف محيط الصدر 70 سم",
      "colors": "المعروض فقط",
      "material": "",
      "description": "فستان عباية من خامة الروز كريب",
      "stock": 4,
      "availability": "متاح",
      "care": "يفضل الغسيل اليدوي",
      "featured": false
    },
    {
      "id": "HN-024",
      "name": "فستان كريب كوري أبيض وأسود",
      "whatsapp_name": "فستان كريب كوري أبيض وأسود",
      "category": "فستان",
      "price": 1100,
      "compare_at": 1350,
      "sizes": "مقاس 52 — نصف محيط الصدر 64 سم",
      "colors": "المعروض فقط",
      "material": "",
      "description": "فستان قطعة واحدة من الكريب الكوري",
      "stock": 1,
      "availability": "متاح",
      "care": "",
      "featured": false
    },
    {
      "id": "HN-025",
      "name": "فستان حرير يوريا زيتوني",
      "whatsapp_name": "فستان حرير يوريا زيتوني",
      "category": "فستان",
      "price": 1250,
      "compare_at": 1550,
      "sizes": "مقاس 40 — نصف محيط الصدر 52 سم | مقاس 42 — نصف محيط الصدر 54 سم | مقاس 44 — نصف محيط الصدر 56 سم | مقاس 46 — نصف محيط الصدر 58 سم",
      "colors": "المعروض فقط",
      "material": "",
      "description": "فستان قطعة واحدة من الحرير اليوريا",
      "stock": 4,
      "availability": "متاح",
      "care": "",
      "featured": false
    },
    {
      "id": "HN-026",
      "name": "فستان كتان فرنسي أخضر فاتح",
      "whatsapp_name": "فستان كتان فرنسي أخضر فاتح",
      "category": "فستان",
      "price": 1250,
      "compare_at": 1600,
      "sizes": "مقاس 40 — نصف محيط الصدر 52 سم | مقاس 42 — نصف محيط الصدر 54 سم | مقاس 44 — نصف محيط الصدر 56 سم | مقاس 46 — نصف محيط الصدر 58 سم",
      "colors": "المعروض فقط",
      "material": "",
      "description": "فستان من الكتان الفرنسي الناعم والمريح",
      "stock": 4,
      "availability": "متاح",
      "care": "",
      "featured": false
    },
    {
      "id": "HN-027",
      "name": "سوت 3 قطع",
      "whatsapp_name": "بدلة 3 قطع",
      "category": "طقم",
      "price": 1400,
      "compare_at": 1600,
      "sizes": "مقاس 2XL محيط الصدر 57 سم",
      "colors": "أسود، أوف وايت",
      "material": "كريب",
      "description": "طقم أنيق بتصميم متعدد الطبقات وعباية خارجية مطبوعة.",
      "stock": 1,
      "availability": "متاح",
      "care": "",
      "featured": false
    },
    {
      "id": "HN-028",
      "name": "مانتو",
      "whatsapp_name": "مانتو بيج",
      "category": "بالطو",
      "price": null,
      "compare_at": null,
      "sizes": "مقاس M نصف محيط الصدر 58- | مقاس XL نصف محيط صدر 66 سم",
      "colors": "رمادي",
      "material": "كتان",
      "description": "مانتو طويل بقصة مستقيمة ورباط خصر",
      "stock": 2,
      "availability": "متاح",
      "care": "",
      "featured": false
    },
    {
      "id": "HN-029",
      "name": "لونج شميز",
      "whatsapp_name": "لونج شميز ستان",
      "category": "فستان",
      "price": 1400,
      "compare_at": 1600,
      "sizes": "المعروض فقط",
      "colors": "رمادي",
      "material": "ستان توكتوك",
      "description": "فستان طويل بطبعة هادئة وقصة مريحة مناسبة للخروجات.",
      "stock": null,
      "availability": "متاح",
      "care": "",
      "featured": false
    },
    {
      "id": "HN-030",
      "name": "سوت قطعتين",
      "whatsapp_name": "طقم تونيك مطرز وبنطلون",
      "category": "طقم",
      "price": 1500,
      "compare_at": 1700,
      "sizes": "مقاس 3XL نصف محيط الصدر 62 سم",
      "colors": "أوف وايت، أحمر",
      "material": "حرير",
      "description": "سوت قطعتين من الحرير المطبوع",
      "stock": 1,
      "availability": "متاح",
      "care": "",
      "featured": false
    },
    {
      "id": "HN-031",
      "name": "عباية كاجوال",
      "whatsapp_name": "فستان بيج بدرجتين",
      "category": "فستان",
      "price": 1500,
      "compare_at": 1700,
      "sizes": "مقاس XL نصف محيط الصدر 66 سم",
      "colors": "بيج، بني",
      "material": "كتان",
      "description": "فستان طويل بتنسيق لونين وقصة أنثوية عملية.",
      "stock": 1,
      "availability": "متاح",
      "care": "",
      "featured": false
    },
    {
      "id": "HN-032",
      "name": "عباية كاجوال برباط",
      "whatsapp_name": "عباية موف برباط",
      "category": "عباية",
      "price": 1500,
      "compare_at": 1700,
      "sizes": "مقاس XL نصف محيط الصدر 64 سم",
      "colors": "موف",
      "material": "كتان",
      "description": "عباية طويلة بتفاصيل أمامية ورباط خصر.",
      "stock": 1,
      "availability": "متاح",
      "care": "",
      "featured": false
    },
    {
      "id": "HN-033",
      "name": "فستان شيفون",
      "whatsapp_name": "فستان شيفون",
      "category": "فستان",
      "price": 990,
      "compare_at": 1250,
      "sizes": "مقاس 48 نصف محيط الصدر 58 سم - مقاس 52 نصف محيط الصدر 62 سم",
      "colors": "أسود، بنفسجي",
      "material": "شيفون كوري",
      "description": "فستان قطعة واحدة من الشيفون الكوري المبطن بالكامل",
      "stock": 2,
      "availability": "متاح",
      "care": "",
      "featured": false
    },
    {
      "id": "HN-034",
      "name": "سوت 3 قطع",
      "whatsapp_name": "سوت 3 قطع",
      "category": "طقم",
      "price": null,
      "compare_at": 1300,
      "sizes": "مقاس 54 نصف محيط الصدر 68 سم",
      "colors": "موف",
      "material": "حرير يوريا وسوفت",
      "description": "سوت 3 قطع بنطلون وكاردي من الحرير اليوريا والبيزيك من السوفت ومطعم بشريط مطرز",
      "stock": 1,
      "availability": "متاح",
      "care": "",
      "featured": false
    },
    {
      "id": "HN-035",
      "name": "فستان بيج بأزرار",
      "whatsapp_name": "فستان بيج بأزرار",
      "category": "فستان",
      "price": 1200,
      "compare_at": 1500,
      "sizes": "مقاس XL نصف محيط الصدر 60 سم",
      "colors": "بيج",
      "material": "كتان",
      "description": "فستان طويل بأزرار أمامية وحزام خصر.",
      "stock": 1,
      "availability": "متاح",
      "care": "",
      "featured": false
    },
    {
      "id": "HN-036",
      "name": "فستان أزرق فاتح مطبوع",
      "whatsapp_name": "فستان أزرق فاتح مطبوع",
      "category": "فستان",
      "price": 1100,
      "compare_at": 1500,
      "sizes": "مقاس 48 نصف محيط الصدر 58 سم",
      "colors": "أزرق فاتح",
      "material": "كريب فوردي",
      "description": "فستان طويل بطبعة ناعمة وأكمام واسعة.",
      "stock": 1,
      "availability": "متاح",
      "care": "",
      "featured": false
    },
    {
      "id": "HN-037",
      "name": "فستان رمادي بنقشة هادئة",
      "whatsapp_name": "فستان رمادي بنقشة هادئة",
      "category": "فستان",
      "price": 1050,
      "compare_at": 1250,
      "sizes": "مقاس 50 محيط الصدر 62 سم",
      "colors": "رمادي",
      "material": "روز كريب",
      "description": "فستان طويل بنقشة هادئة وقصة انسيابية.",
      "stock": 1,
      "availability": "متاح",
      "care": "",
      "featured": false
    },
    {
      "id": "HN-038",
      "name": "سوت سوارية",
      "whatsapp_name": "طقم أسود ثلاث قطع",
      "category": "طقم",
      "price": 1350,
      "compare_at": 1550,
      "sizes": "مقاس XL محيط الصدر 60 سم",
      "colors": "أسود",
      "material": "البيزيك والبنطلون سوفت يوريا والكاردي شيفون مطرز بالترتر",
      "description": "بدلة سوارية 3 قطع",
      "stock": 1,
      "availability": "متاح",
      "care": "",
      "featured": false
    },
    {
      "id": "HN-039",
      "name": "عباية أسود بأكمام بيج",
      "whatsapp_name": "عباية أسود بأكمام بيج",
      "category": "فستان",
      "price": 1100,
      "compare_at": 1400,
      "sizes": "مقاس 54 نصف محيط الصدر 64 سم",
      "colors": "أسود، بيج",
      "material": "حرير يوريا",
      "description": "عباية أسود من الحرير اليوريا وأكمام بيج بسوستة أمامية طويلة",
      "stock": 1,
      "availability": "متاح",
      "care": "",
      "featured": false
    },
    {
      "id": "HN-040",
      "name": "فستان قطعة واحدة",
      "whatsapp_name": "فستان قطعة واحدة",
      "category": "فستان",
      "price": 990,
      "compare_at": 1200,
      "sizes": "مقاس 50 نصف محيط الصدر 64 سم",
      "colors": "أسود، متعدد الألوان",
      "material": "حرير يوريا وشيفون",
      "description": "فستان قطعة واحدة من الحرير اليوريا وقطعة من الشيفون لتعطي إحساس القطعتين",
      "stock": 1,
      "availability": "متاح",
      "care": "",
      "featured": false
    },
    {
      "id": "HN-041",
      "name": "عباية بأزرار",
      "whatsapp_name": "لونج شميز تركواز مطبوع",
      "category": "لونج شميز",
      "price": 990,
      "compare_at": 1200,
      "sizes": "مقاس 52 نصف محيط الصدر 68 سم",
      "colors": "تركواز",
      "material": "روز كريب",
      "description": "لونج شميز بطبعة هندسية وقصة واسعة.",
      "stock": 1,
      "availability": "متاح",
      "care": "",
      "featured": false
    },
    {
      "id": "HN-042",
      "name": "فستان ستان",
      "whatsapp_name": "فستان ستان أخضر فاتح",
      "category": "فستان",
      "price": 990,
      "compare_at": 1200,
      "sizes": "مقاس 44 نصف محيط الصدر 56 سم",
      "colors": "أخضر فاتح",
      "material": "ستان",
      "description": "فستان طويل بطبعة نباتية هادئة وقصة مريحة.",
      "stock": 1,
      "availability": "متاح",
      "care": "",
      "featured": false
    },
    {
      "id": "HN-043",
      "name": "عباية قطعتين",
      "whatsapp_name": "عباية مفتوحة مطبوعة موف",
      "category": "عباية",
      "price": 1100,
      "compare_at": 1500,
      "sizes": "مقاس 46 نصف محيط الصدر 56 سم",
      "colors": "موف، متعدد الألوان",
      "material": "البيزيك حرير يوريا والكاردي شيفون",
      "description": "عباية أوبن قطعتين بيزيك من الحرير اليوريا والكاردي من الشيفون الكوري وشريط مطرز",
      "stock": 1,
      "availability": "متاح",
      "care": "",
      "featured": false
    },
    {
      "id": "HN-044",
      "name": "فستان كوريشة",
      "whatsapp_name": "فستان أوف وايت مطبوع",
      "category": "فستان",
      "price": 990,
      "compare_at": 1200,
      "sizes": "مقاس 44 نصف محيط الصدر 54 سم",
      "colors": "أوف وايت، متعدد الألوان",
      "material": "كوريشة",
      "description": "فستان طويل بطبعة رقيقة وألوان هادئة.",
      "stock": 1,
      "availability": "متاح",
      "care": "",
      "featured": false
    },
    {
      "id": "HN-045",
      "name": "فستان قطعتين",
      "whatsapp_name": "طقم مينت بجاكيت قصير",
      "category": "طقم",
      "price": 1350,
      "compare_at": 1500,
      "sizes": "مقاس 44 نصف محيط الصدر 56 سم",
      "colors": "مينت",
      "material": "روزالين تركي",
      "description": "طقم فستان بحملات وعليه جاكيت قصير وإكسسوارات مميزة",
      "stock": 1,
      "availability": "متاح",
      "care": "",
      "featured": false
    },
    {
      "id": "HN-046",
      "name": "فستان قطعتين",
      "whatsapp_name": "فستان رمادي بفيونكة",
      "category": "فستان",
      "price": 1300,
      "compare_at": 1500,
      "sizes": "مقاس 40 نصف محيط الصدر 52 سم - مقاس 42 نصف محيط الصدر 54 سم",
      "colors": "رمادي",
      "material": "كتان فرنساوي",
      "description": "طقم فستان بحملات وعليه جاكيت قصير وإكسسوارات مميزة",
      "stock": 2,
      "availability": "متاح",
      "care": "",
      "featured": false
    },
    {
      "id": "HN-047",
      "name": "عباية سوداء بأكمام شفافة",
      "whatsapp_name": "عباية سوداء بأكمام شفافة",
      "category": "عباية",
      "price": 1300,
      "compare_at": 1470,
      "sizes": "مقاس 46 نصف محيط الصدر 54 سم",
      "colors": "أسود",
      "material": "شيفون وحرير",
      "description": "عباية حرير وشيفون تحت بطانة من الستان لتعطي إحساس بالأناقة",
      "stock": 1,
      "availability": "متاح",
      "care": "",
      "featured": false
    },
    {
      "id": "HN-048",
      "name": "فستان سماوي طويل",
      "whatsapp_name": "فستان سماوي طويل",
      "category": "فستان",
      "price": 850,
      "compare_at": 1100,
      "sizes": "مقاس L نصف محيط الصدر 52 سم - مقاس 3XL نصف محيط الصدر 58 سم",
      "colors": "سماوي",
      "material": "روزالين قطن",
      "description": "فستان طويل بلون سماوي وقصة انسيابية.",
      "stock": 2,
      "availability": "متاح",
      "care": "",
      "featured": false
    }
  ]
};
